tap "felixkratz/formulae"
tap "homebrew/bundle"
tap "homebrew/services"
tap "nikitabobko/tap"
brew "ack"
brew "atuin"
brew "sqlite"
brew "awscli"
brew "binwalk"
brew "chezmoi"
brew "cloc"
brew "colima"
brew "colordiff"
brew "coreutils"
brew "curl"
brew "docker"
brew "docker-buildx"
brew "ffmpeg"
brew "flock"
brew "fzf"
brew "gawk"
brew "gh"
brew "git-filter-repo"
brew "glab"
brew "gnupg"
brew "htop"
brew "hurl"
brew "imagemagick"
brew "ipcalc"
brew "iperf"
brew "iproute2mac"
brew "jj"
brew "jq"
brew "kubernetes-cli"
brew "lnav"
brew "mas"
brew "mpv"
brew "mtr"
brew "ncdu"
brew "neovim"
brew "nethack"
brew "nmap"
brew "openssh"
brew "pre-commit"
brew "pv"
brew "pwgen"
brew "ranger"
brew "socat"
brew "sshuttle"
brew "tmux"
brew "wget"
brew "yh"
brew "zsh-syntax-highlighting"
brew "felixkratz/formulae/sketchybar"
cask "1password"
cask "aerospace"
cask "audacity"
cask "font-hack-nerd-font"
cask "gimp"
cask "google-chrome"
cask "keepassxc"
cask "mullvadvpn"
cask "openlens"
cask "raycast"
cask "slack"
cask "stretchly"
cask "wezterm@nightly"
cask "wireshark"
cask "zed"
cask "zoom"
mas "Accelerate", id: 1459809092
mas "AdGuard for Safari", id: 1440147259
mas "Dark Reader for Safari", id: 1438243180
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Refined GitHub", id: 1519867270
mas "Tailscale", id: 1475387142
mas "Telegram", id: 747648890
mas "Things", id: 904280696
mas "Vimari", id: 1480933944
