tap "felixkratz/formulae"
tap "gcenx/wine"
tap "golangci/tap"
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/services"
tap "nikitabobko/tap"
tap "playcover/playcover"
brew "ack"
brew "atuin"
brew "autoconf"
brew "automake"
brew "awscli"
brew "azure-cli"
brew "binwalk"
brew "glib"
brew "cairo"
brew "capstone"
brew "chezmoi"
brew "cloc"
brew "cmake"
brew "lima"
brew "colima"
brew "colordiff"
brew "coreutils"
brew "curl"
brew "diffoscope"
brew "docker"
brew "docker-buildx"
brew "eksctl"
brew "elvish"
brew "harfbuzz"
brew "openjdk"
brew "emscripten"
brew "tesseract"
brew "ffmpeg"
brew "flock"
brew "fzf"
brew "gawk"
brew "gh"
brew "ghostscript"
brew "git-filter-repo"
brew "glab"
brew "gnupg"
brew "go"
brew "goreleaser"
brew "libtool"
brew "graphviz"
brew "hcl2json"
brew "htop"
brew "hurl"
brew "icu4c@75"
brew "libheif"
brew "liblqr"
brew "imagemagick"
brew "ipcalc"
brew "iperf"
brew "iproute2mac"
brew "jd"
brew "jj"
brew "jq"
brew "kubernetes-cli"
brew "libirecovery"
brew "libraqm"
brew "libusb-compat"
brew "llvm@16"
brew "lnav"
brew "mas"
brew "yt-dlp"
brew "mpv"
brew "mtr"
brew "ncdu"
brew "neovim"
brew "nethack"
brew "ninja"
brew "nmap"
brew "numpy"
brew "openjdk@17"
brew "openssh"
brew "pillow"
brew "pkgconf"
brew "pre-commit"
brew "protobuf"
brew "pv"
brew "pwgen"
brew "pyenv"
brew "qemu"
brew "qpdf"
brew "ranger"
brew "sdl2_image"
brew "sdl2_mixer"
brew "sdl2_ttf"
brew "sequoia-sq"
brew "socat"
brew "sshuttle"
brew "switchaudio-osx"
brew "tea"
brew "terragrunt"
brew "tmux"
brew "watch"
brew "wget"
brew "yh"
brew "zsh-syntax-highlighting"
brew "felixkratz/formulae/sketchybar"
brew "golangci/tap/golangci-lint"
brew "hashicorp/tap/terraform"
cask "1password"
cask "1password-cli"
cask "aerospace"
cask "android-platform-tools"
cask "android-studio"
cask "audacity"
cask "calibre"
cask "font-hack-nerd-font"
cask "ghidra"
cask "gimp"
cask "google-chrome"
cask "google-cloud-sdk"
cask "iterm2"
cask "itermai"
cask "jetbrains-toolbox"
cask "karabiner-elements"
cask "keepassxc"
cask "kegworks"
cask "lunar"
cask "mac-mouse-fix"
cask "mitmproxy"
cask "mullvadvpn"
cask "openlens"
cask "playcover-community"
cask "qbittorrent"
cask "raycast"
cask "session-manager-plugin"
cask "slack"
cask "steam"
cask "stretchly"
cask "utm"
cask "vagrant"
cask "wezterm@nightly"
cask "wireshark"
cask "yellowdot"
cask "zed"
cask "zoom"
mas "Accelerate", id: 1459809092
mas "AdGuard for Safari", id: 1440147259
mas "Apple Configurator", id: 1037126344
mas "CustomSearch", id: 1588019370
mas "Dark Reader for Safari", id: 1438243180
mas "Hush", id: 1544743900
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Outline", id: 1356178125
mas "Pages", id: 409201541
mas "Refined GitHub", id: 1519867270
mas "reMarkable", id: 1276493162
mas "Tailscale", id: 1475387142
mas "Telegram", id: 747648890
mas "Things", id: 904280696
mas "Vimari", id: 1480933944
mas "Xcode", id: 497799835
