[user]
name = "Ilya Lukyanov"
email = "ilya@luk.moe"

[ui]
default-description = "DVO-"
default-command = "st"
#show-cryptographic-signatures = true

[signing]
behavior = "own"
backend = "ssh"

key = "~/.ssh/id_ed25519.pub"
#backends.ssh.allowed-signers = "~/.ssh/allowed_signers"

[git]
push-bookmark-prefix = "ilyaluk/push-"

[template-aliases]
# Uppercase change ids. `jj` treats change and commit ids as case-insensitive.
'format_short_change_id(id)' = 'id.shortest(12).prefix().upper() ++ "[" ++ id.shortest(12).rest() ++ "]"'

[fix.tools.tf-fmt]
command = ["terraform", "fmt", "-"]
patterns = ["glob:'**/*.tf'"]

[fix.tools.tg-hclfmt]
command = ["tg-fmt"]
patterns = ["glob:'**/terragrunt.hcl'"]
